name: asl_flutter
description: Professional ASL Flutter mobile application for archaeological artifact verification on Internet Computer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # State Management (Professional)
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Network & Backend (Professional)
  dio: ^5.4.0
  retrofit: ^4.0.3
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.2
  connectivity_plus: ^5.0.2
  
  # Internet Computer Integration
  agent_dart: ^1.0.0
  
  # Storage & Persistence (Professional)
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  secure_storage: ^3.3.5
  
  # Image & Media (Professional)
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  image_cropper: ^5.0.1
  file_picker: ^6.1.1
  
  # Navigation (Professional)
  go_router: ^13.0.1
  auto_route: ^7.9.2
  
  # UI Components (Professional)
  shimmer: ^3.0.0
  lottie: ^2.7.0
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  skeleton_text: ^3.0.1
  
  # Forms & Validation (Professional)
  reactive_forms: ^16.1.1
  form_validator: ^2.1.1
  
  # Date & Time
  intl: ^0.19.0
  timeago: ^3.6.0
  
  # Charts & Analytics (Professional)
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^24.1.41
  
  # Utils (Professional)
  uuid: ^4.2.1
  crypto: ^3.0.3
  path_provider: ^2.1.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # Authentication & Security
  local_auth: ^2.1.7
  biometric_storage: ^5.1.0
  
  # Logging & Error Handling (Professional)
  logger: ^2.0.2+1
  flutter_logs: ^2.1.12
  sentry_flutter: ^7.13.2
  
  # Real-time & WebSocket
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  
  # Serialization (Professional)
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # HTTP Alternative
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation (Professional)
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  
  # Testing (Professional)
  mocktail: ^1.0.1
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  network_image_mock: ^2.1.1
  
  # Analysis & Quality (Professional)
  dart_code_metrics: ^5.7.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/lottie/
    - assets/fonts/
    - assets/config/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700